name: CI Pipeline

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Running SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          export PATH=$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin
          sonar-scanner -Dsonar.token=squ_85e1cc240055ef57e5c4f94238922f29dc93b08b

      # - name: Run Reviewdog flake8
      #   uses: reviewdog/action-flake8@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-pr-review
      #     level: error

      # - name: Run Reviewdog black
      #   uses: reviewdog/action-black@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     reporter: github-pr-review
      #     level: info

      # - name: Checking out changes in the develop branch
      #   run: |
      #     git checkout develop
      #     git pull
      #     git log --oneline --graph
