name: Reviewdog

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Перевірка змін у гілці develop
        run: |
          git fetch origin
          git checkout origin/develop
          git log --oneline --graph -n 20 > develop_changes.txt
          cat develop_changes.txt

      - name: Збереження develop log як артефакт
        uses: actions/upload-artifact@v4
        with:
          name: develop-commits-log
          path: develop_changes.txt
